variable "region" {}
variable "instance_type" {}
variable "project_name" {}
variable "project1_name" {}
variable "project2_name" {}
variable "vpc_cidr" {}
variable "vpc_id" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet_az1_cidr" {}
variable "private_subnet_az2_cidr" {}
variable "domain_name" {}
variable "alternative_name" {}
variable "public_subnet_az1_id" {}
variable "public_subnet_az2_id" {}
variable "private_subnet_az1_id" {}
variable "private_subnet_az2_id" {}
variable "internet_gateway" {}
variable "ami" {}
variable "certificate_arn" {}
variable "test_security_group_id" {}
variable "security_group" {}
variable "record_name" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}
variable "lb_subnet" {}
variable "key_name" {}
variable "image_id" {}
variable "userpool_name" {}
variable "client_name" {}