name: Terraform CI CD pipeline for deploying AWS services
run-name: ${{github.actor}} has trigger the pipeline

on:
  push:
    branches:
      - "dev"

env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform:
    # name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ">=5.0.0"

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./main-code

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./main-code

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./main-code

      - name: Terraform Apply
        id: apply
        run: terraform apply
        working-directory: ./main-code
